ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - name: chartmuseum.34.159.243.248.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.34.159.243.248.nip.io
env:
  open:
    # storage backend, can be one of: local, alibaba, amazon, google, microsoft, oracle
    STORAGE: local
  #   # gcs bucket to store charts for google storage backend
  #   STORAGE_GOOGLE_BUCKET: infra-bucket777
  #   # prefix to store charts for google storage backend
  #   STORAGE_GOOGLE_PREFIX: ""
  #   # container to store charts for microsoft storage backend
  #   CHART_POST_FORM_FIELD_NAME: chart
  #   # form field which will be queried for the provenance file content
  #   PROV_POST_FORM_FIELD_NAME: prov
  #   # levels of nested repos for multitenancy. The default depth is 0 (singletenant server)
  #   DEPTH: 0
  #   # show debug messages
  #   DEBUG: true
  #   # output structured logs as json
  #   LOG_JSON: true
  #   # disable use of index-cache.yaml
  #   DISABLE_STATEFILES: false
  #   # disable Prometheus metrics
  #   DISABLE_METRICS: true
  #   # disable all routes prefixed with /api
  #   DISABLE_API: true
  #   # allow chart versions to be re-uploaded
  #   ALLOW_OVERWRITE: false
  #   # absolute url for .tgzs in index.yaml
  #   CHART_URL:
  #   # allow anonymous GET operations when auth is used
  #   AUTH_ANONYMOUS_GET: false
  #   # sets the base context path
  #   CONTEXT_PATH:
  #   # parallel scan limit for the repo indexer
  #   INDEX_LIMIT: 0
  #   # cache store, can be one of: redis (leave blank for inmemory cache)
  #   CACHE:
  #   # address of Redis service (host:port)
  #   CACHE_REDIS_ADDR:
  #   # Redis database to be selected after connect
  #   CACHE_REDIS_DB: 0
  #   # enable bearer auth
  #   BEARER_AUTH: false
  #   # auth realm used for bearer auth
  #   AUTH_REALM:
  #   # auth service used for bearer auth
  #   AUTH_SERVICE:
  # # field:
  # #   # POD_IP: status.podIP
  # secret:
  # #   # username for basic http authentication
  # #   BASIC_AUTH_USER: admin
  # #   # password for basic http authentication
  # #   BASIC_AUTH_PASS: password
  # #   # GCP service account json file
  #   GOOGLE_CREDENTIALS_JSON: { "type": "service_account", "project_id": "infra-335109" , "private_key_id": "a00373c1faf5166dae32899bc9942933755e470e", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDFib957A5cx6dM\nhFwctKGSJFRpT4OadKP7n6HVN2dTvgDBdXox4kmWwi4vv3I0tXiYV9U4iYy5/Kgi\nWKlIJxZcNPi0bbrjweB7rLBAp6+Cg0d/LtxlXjNPUSdswrdWxyR9ZnZYm37eVhXf\nJXEcHiitTajHrp+FFlEbAui0rdwdXYYWIR+cNJPh3ySPYT9PhWUv5rlM23o1lUdp\n5zckKtJF5EBTTMZUwBxkibbr3QQ5SH+lU6fFfvyk9RwxSVYHBrLnj8+TQ7XCdZrx\nxHLOdILLsDadTE6LsE556dxMVNywqipVNVOWuOnabYambYyDv+TO04ECIdIKu1q3\nNC+WdpglAgMBAAECggEAWclxP31Ez/Yt/HEjHycZU4Bw38c1FdUTnjEiUXRT4nP4\nCvcXWio1cbGEZc6anguoK3Ks53xZ+0W0tJvhIfsmRjYLn5NKwfBjVUOaf2DYvTVn\nn48QvYCSSOilx2FADVEKLHeQrljLU0sEuP9fSL0Kly832r9sIYWRyvnJBSsLZErK\n9BaGZFv6Flt5fIWeRnQU1T4NqGF9BM/jzrWI0BaJOyAPQososRZVQakgGuEXSuHs\n6KPUuyGo8hd7KzitllptRBkKE0/zzYSJVBN7GDLj+FY/OF/9wkaXKTH451Ioa9IG\ntuLXyoSV1bXGCgY8TOZ+yQ5X+eQnnkvJ8DFAiWXQpwKBgQD8hM+SZf3OVAnGx5gK\n7pUaORo4KBxoMEfeMM8Oj2yQquNX3eUsAMqju3gi3s4RQSAJ/kPtuLsO4tELTNwm\ncVIynGZP/lYwAy0cjANOdbZ94CNiszr2QuJiZWnQsws5QTvETsBMrSxv09NkXjqV\nTo6cv0jtm41JWm5z6bw3J/fvMwKBgQDIQuYzaRzRiii2Jb4NKxTvUevROOXZ8EG0\ngCiq0Qj+ruirfPfR17L8Xdn0yL1FYG9PRYXN1Vkv8lLFjmX8Xnnju9AZPyJs9mxT\n0WQCGSxUTw2OPgu0wuL5OfA+DRlKjqCsNDTVS+cl6QZx+9ksb/a6wTX+gBt5wLuW\n2WdpiyO7RwKBgBcaX5NZWXtDHRHeuP5nDaU0jD2PDepKYIjnlkoSvTAPMnWbi5gX\nCnMod7lZASl6999yL+zT9elKvy11fr7Vp1uSC5pN/rytzbbK6JKJGoUxuIsTMtXN\nEMFH3gKGHwTB/yHawqVBQsuIadLI/Dsk0M9ugNGcZbTMXUaln967/WcZAoGAMube\nQF8NVi1536KERjCXJ6V4/TsrIVQyP0D8FT8AvEuVFFG1Y/8hnYf1aITFpya15D5V\nnlYGT2uWomRpg9Y3wSzx3hjwFSYlrsBgXTAs1lkppugabZ3Dt3mEmSEXNp4+NMco\nTrb2T+qFGt/a+bKT0jBeGwxQ74ePpu4nnOoi8O0CgYAax9bRqmd/T5XieYjdBrzB\n3RxnQCcoQH2SGI2/Dlop6ARNd34Q/QET9rwjfKlDVvcoJ2lPdW3Oc54d7bATKElc\nFejh5Tr8BVADEmi4R0kH4GiINi/UFD7JOY6yiuRAdBeD7qOd1dhCG1eWHiCE546L\nDAIt9LplmH8Mf481tSOXtQ==\n-----END PRIVATE KEY-----\n", "client_email": "k8s-232@infra-335109.iam.gserviceaccount.com", "client_id": "111470070215354263112", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/k8s-232%40infra-335109.iam.gserviceaccount.com" }

  # #   # Redis requirepass server configuration
  # #   CACHE_REDIS_PASSWORD:
  # # # Name of an existing secret to get the secret values ftom
  # # existingSecret:
  # # # Stores Enviromnt Variable to secret key name mappings
  # existingSecretMappings:
  # #   # username for basic http authentication
  # #   BASIC_AUTH_USER: admin
  # #   # password for basic http authentication
  # #   BASIC_AUTH_PASS: password
  # #   # GCP service account json file
  #   GOOGLE_CREDENTIALS_JSON: { "type": "service_account", "project_id": "infra-335109" , "private_key_id": "a00373c1faf5166dae32899bc9942933755e470e", "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDFib957A5cx6dM\nhFwctKGSJFRpT4OadKP7n6HVN2dTvgDBdXox4kmWwi4vv3I0tXiYV9U4iYy5/Kgi\nWKlIJxZcNPi0bbrjweB7rLBAp6+Cg0d/LtxlXjNPUSdswrdWxyR9ZnZYm37eVhXf\nJXEcHiitTajHrp+FFlEbAui0rdwdXYYWIR+cNJPh3ySPYT9PhWUv5rlM23o1lUdp\n5zckKtJF5EBTTMZUwBxkibbr3QQ5SH+lU6fFfvyk9RwxSVYHBrLnj8+TQ7XCdZrx\nxHLOdILLsDadTE6LsE556dxMVNywqipVNVOWuOnabYambYyDv+TO04ECIdIKu1q3\nNC+WdpglAgMBAAECggEAWclxP31Ez/Yt/HEjHycZU4Bw38c1FdUTnjEiUXRT4nP4\nCvcXWio1cbGEZc6anguoK3Ks53xZ+0W0tJvhIfsmRjYLn5NKwfBjVUOaf2DYvTVn\nn48QvYCSSOilx2FADVEKLHeQrljLU0sEuP9fSL0Kly832r9sIYWRyvnJBSsLZErK\n9BaGZFv6Flt5fIWeRnQU1T4NqGF9BM/jzrWI0BaJOyAPQososRZVQakgGuEXSuHs\n6KPUuyGo8hd7KzitllptRBkKE0/zzYSJVBN7GDLj+FY/OF/9wkaXKTH451Ioa9IG\ntuLXyoSV1bXGCgY8TOZ+yQ5X+eQnnkvJ8DFAiWXQpwKBgQD8hM+SZf3OVAnGx5gK\n7pUaORo4KBxoMEfeMM8Oj2yQquNX3eUsAMqju3gi3s4RQSAJ/kPtuLsO4tELTNwm\ncVIynGZP/lYwAy0cjANOdbZ94CNiszr2QuJiZWnQsws5QTvETsBMrSxv09NkXjqV\nTo6cv0jtm41JWm5z6bw3J/fvMwKBgQDIQuYzaRzRiii2Jb4NKxTvUevROOXZ8EG0\ngCiq0Qj+ruirfPfR17L8Xdn0yL1FYG9PRYXN1Vkv8lLFjmX8Xnnju9AZPyJs9mxT\n0WQCGSxUTw2OPgu0wuL5OfA+DRlKjqCsNDTVS+cl6QZx+9ksb/a6wTX+gBt5wLuW\n2WdpiyO7RwKBgBcaX5NZWXtDHRHeuP5nDaU0jD2PDepKYIjnlkoSvTAPMnWbi5gX\nCnMod7lZASl6999yL+zT9elKvy11fr7Vp1uSC5pN/rytzbbK6JKJGoUxuIsTMtXN\nEMFH3gKGHwTB/yHawqVBQsuIadLI/Dsk0M9ugNGcZbTMXUaln967/WcZAoGAMube\nQF8NVi1536KERjCXJ6V4/TsrIVQyP0D8FT8AvEuVFFG1Y/8hnYf1aITFpya15D5V\nnlYGT2uWomRpg9Y3wSzx3hjwFSYlrsBgXTAs1lkppugabZ3Dt3mEmSEXNp4+NMco\nTrb2T+qFGt/a+bKT0jBeGwxQ74ePpu4nnOoi8O0CgYAax9bRqmd/T5XieYjdBrzB\n3RxnQCcoQH2SGI2/Dlop6ARNd34Q/QET9rwjfKlDVvcoJ2lPdW3Oc54d7bATKElc\nFejh5Tr8BVADEmi4R0kH4GiINi/UFD7JOY6yiuRAdBeD7qOd1dhCG1eWHiCE546L\nDAIt9LplmH8Mf481tSOXtQ==\n-----END PRIVATE KEY-----\n", "client_email": "k8s-232@infra-335109.iam.gserviceaccount.com", "client_id": "111470070215354263112", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/k8s-232%40infra-335109.iam.gserviceaccount.com" }


  # #   # Redis requirepass server configuration
  # #   CACHE_REDIS_PASSWORD:
